// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	SenderID  uuid.UUID
	RoomID    uuid.UUID
}

type Room struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatorID uuid.NullUUID
	OwnerID   uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
